### ISSUE TITLE
Can't craft certain machines

### ISSUE THREAD

**Issue by adras** [Xenos6666/TPT2_scripts#1]
I just tried to craft all basic machines, to either tier 1 or tier 3.

The following worked:

- Boiler
- Refiner

The following didn't work:
- Cutter
- Presser (not supposed to work for t1, but also didn't work with a t1 in inventory trying to craft t2)
- Crusher
- Oven

In order to check I'm not out of material I crafted the ones that didn't work manually, which worked. So I had the right amount of resources.

Is there any way to figure out why certain machines don't work?

**Comment by Xenos6666** [comment]
Sorry, I forgot to setup notifications for this account and I don't check it very often. If it's not too late could you give me more info on the issue? Like screenshots of your inventory for example? I'm assuming you're probably not actively playing the game anymore at that point so I'll probably close this soon, sorry about not noticing this sooner :/

**Comment by adras** [comment]
Yeah, you're right, I no longer play the game. And I think, I messed something up during setting up the scripts. Or as you assumed, something was wrong with my inventory. In the end I got it fixed. Thanks for the reply though
